
services:
  MyDbPostgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_CONTAINER_IMAGE_NAME}
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - "${POSTGRES_PORTS}:5432"


  Pg_Admin:
    depends_on:
      - MyDbPostgres
    container_name: PgAdmin
    image: dpage/pgadmin4:6.17
    volumes:
      - Pg_Admin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - "${PGADMIN_PORTS}:80"

  Redis:
    container_name: Redis_Cache
    image: redis:7.4.1-alpine3.20
    volumes:
      - Redis_Cache:/data redis/redis-stack:latest
    environment:
      - REDIS_ARGS:${REDIS_ARGS}
      - REDISEARCH_ARGS:${REDISEARCH_ARGS}
    ports:
    - ${REDIS_PORTS}:6579


volumes:
  postgresql:
    external: false
  Pg_Admin:
    external: false
  Redis_Cache:
    